### ISSUE TITLE
Add information on how to use localy

### ISSUE THREAD

**Issue by TimGeibel** [remy/inliner#25]
Hi!

Finaly managed to install this (had to install command line tools first via xCode). Now I tried to inline a project that is on my localhost. I tried it with these commands:

inliner /Path/to/my/project/root > index.html
inliner http://localhost > index.html
inliner http://virtual-host.local > index.html

Would normaly all of those commands work? If not, which one should it be? And do I have to be in the project's folder when running this, or should I be in the folder where I want the output to be located or do I just define origin -> target in the command? An example for this case in the readme file would be very helpful.

Besides this being unclear I'm always getting this error (started this script in the folder where I wanted to place the output):

TypeError: Cannot call method 'request' of undefined
    at Inliner.makeRequest (/usr/local/lib/node_modules/inliner/inliner.js:553:53)
    at Inliner.get (/usr/local/lib/node_modules/inliner/inliner.js:360:17)
    at Object.inliner.get.jsdom.env.todo.styles.assets.styles.each.style (/usr/local/lib/node_modules/inliner/inliner.js:153:19)
    at Function.b.extend.each (http://code.jquery.com/jquery.min.js:3:5257)
    at b.fn.b.each (http://code.jquery.com/jquery.min.js:3:2013)
    at /usr/local/lib/node_modules/inliner/inliner.js:150:38
    at exports.env.exports.jsdom.env.scriptComplete (/usr/local/lib/node_modules/inliner/node_modules/jsdom/lib/jsdom.js:207:39)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

Thx for any help/info.

**Comment by remy** [comment]
This is fixed @ 1.0.0.
