### ISSUE TITLE
TypeError: Cannot call method 'request' of undefined

### ISSUE THREAD

**Issue by tfriedel** [remy/inliner#27]
I get this error running on windows 8 with node 0.10.4:

C:\Users\Thomas\AppData\Roaming\npm\node_modules\inliner\inliner.js:553
  return http[oURL.protocol.slice(0, -1) || 'http'].request(options);
                                                    ^
TypeError: Cannot call method 'request' of undefined
    at Inliner.makeRequest (C:\Users\Thomas\AppData\Roaming\npm\node_modules\inliner\inliner.js:553:53)
    at Inliner.get (C:\Users\Thomas\AppData\Roaming\npm\node_modules\inliner\inliner.js:360:17)
    at Object.<anonymous> (C:\Users\Thomas\AppData\Roaming\npm\node_modules\inliner\inliner.js:153:19)
    at Function.b.extend.each (http://code.jquery.com/jquery.min.js:3:5257)
    at b.fn.b.each (http://code.jquery.com/jquery.min.js:3:2013)
    at C:\Users\Thomas\AppData\Roaming\npm\node_modules\inliner\inliner.js:150:38
    at C:\Users\Thomas\AppData\Roaming\npm\node_modules\inliner\node_modules\jsdom\lib\jsdom.js:207:39
    at process._tickCallback (node.js:415:13)

**Comment by remy** [comment]
This should be fixed @ 1.0.0.
