### ISSUE TITLE
Parameter 'url' must be a string, not object

### ISSUE THREAD

**Issue by jussi-kalliokoski** [remy/inliner#31]
When I tried running

```sh
$ inliner http://localhost:8158/
```

I get this error:

```
url.js:107
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not object
    at Url.parse (url.js:107:11)
    at urlParse (url.js:101:5)
    at Url.resolve (url.js:409:29)
    at Object.urlResolve [as resolve] (url.js:405:40)
    at Object.<anonymous> (/home/jussi/Code/doctor-reader/node_modules/inliner/inliner.js:269:31)
    at Function.x.extend.each (http://code.jquery.com/jquery.min.js:4:5347)
    at x.fn.x.each (http://code.jquery.com/jquery.min.js:4:1999)
    at /home/jussi/Code/doctor-reader/node_modules/inliner/inliner.js:267:40
    at /home/jussi/Code/doctor-reader/node_modules/inliner/node_modules/jsdom/lib/jsdom.js:207:39
    at process._tickCallback (node.js:415:13)
```

System information:

```sh
$ uname -r
3.10.6-2-ARCH
$ npm version
{ http_parser: '1.0',
  node: '0.10.15',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.13',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e',
  npm: '1.3.5' }
```

**Comment by AndrewSav** [comment]
Same problem. It still seems not to be updated.

**Comment by monbro** [comment]
Yes still having this error as well..

**Comment by remy** [comment]
This is fixed @ 1.0.0.

**Comment by martip-sainsburys** [comment]
Hey what was the issue??

**Comment by remy** [comment]
Total rewrite from the ground up
